(() => {
  'use strict';
  const canvas = document.querySelector('#gameCanvas'), ctx = canvas.getContext('2d');
  const titleScreen = document.querySelector('#titleScreen'), resultScreen = document.querySelector('#resultScreen'), hud = document.querySelector('#hud');
  const W = 2400, H = 1400, TAU = Math.PI * 2;
  const keys = Object.create(null), touch = { x:0, y:0, active:false }, pointer = { x:0, y:0 };
  let dpr = 1, raf = 0, last = 0, audio = null, state = 'title', elapsed = 0, alerts = 0, shake = 0;
  const player = { x:250, y:1160, r:18, stamina:100, hidden:false, safe:false };
  const oni = { x:1050, y:690, r:26, speed:110, state:'patrol', target:null };
  const home = { x:2140, y:220, w:190, h:130 };
  const hideSpots = [{x:620,y:1020,r:48,label:'公園の植え込み'},{x:1260,y:1110,r:46,label:'コインランドリー'},{x:1740,y:580,r:46,label:'高架下'}];
  const roads = [{x:80,y:190,w:2240,h:190},{x:80,y:590,w:2240,h:190},{x:80,y:990,w:2240,h:190},{x:300,y:80,w:180,h:1240},{x:930,y:80,w:180,h:1240},{x:1560,y:80,w:180,h:1240},{x:2050,y:80,w:180,h:1240}];
  const buildings = [{x:80,y:80,w:210,h:110},{x:500,y:80,w:390,h:110},{x:1140,y:80,w:370,h:110},{x:1770,y:80,w:250,h:110},{x:80,y:400,w:210,h:170},{x:500,y:400,w:390,h:170},{x:1140,y:400,w:370,h:170},{x:1770,y:400,w:250,h:170},{x:80,y:800,w:210,h:170},{x:500,y:800,w:390,h:170},{x:1140,y:800,w:370,h:170},{x:1770,y:800,w:250,h:170},{x:80,y:1200,w:210,h:110},{x:500,y:1200,w:390,h:110},{x:1140,y:1200,w:370,h:110},{x:1770,y:1200,w:250,h:110}];
  const lights = Array.from({length:42}, (_,i) => ({ x:130 + (i*173)%2050, y:155 + (i*257)%1080, phase:i%5 }));
  function resize() { dpr=Math.min(devicePixelRatio||1,2); canvas.width=innerWidth*dpr; canvas.height=innerHeight*dpr; canvas.style.width=innerWidth+'px'; canvas.style.height=innerHeight+'px'; ctx.setTransform(dpr,0,0,dpr,0,0); }
  function unlockAudio() { if (!audio) audio = new (window.AudioContext||window.webkitAudioContext)(); if (audio.state==='suspended') audio.resume(); }
  function beep(freq=440,dur=.08,type='sine',gain=.025) { if(!audio) return; const o=audio.createOscillator(), g=audio.createGain(); o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur); }
  function start() { unlockAudio(); state='playing'; elapsed=0;alerts=0;player.x=250;player.y=1160;player.stamina=100;player.hidden=false;oni.x=1050;oni.y=690;oni.state='patrol'; titleScreen.classList.add('hidden'); resultScreen.classList.add('hidden'); hud.classList.remove('hidden'); document.querySelector('#mobileControls').classList.remove('hidden'); document.querySelector('#hint').classList.remove('hidden'); beep(330,.12,'triangle'); last=performance.now(); cancelAnimationFrame(raf); raf=requestAnimationFrame(loop); }
  function finish(win, reason) { state=win?'won':'lost'; document.querySelector('#mobileControls').classList.add('hidden'); hud.classList.add('hidden'); resultScreen.classList.remove('hidden'); document.querySelector('#resultMark').textContent=win?'✓':'×'; document.querySelector('#resultMark').style.color=win?'var(--cyan)':'var(--danger)'; document.querySelector('#resultKicker').textContent=win?'MISSION COMPLETE':'SIGNAL LOST'; document.querySelector('#resultTitle').textContent=win?'帰宅成功':'見つかった'; document.querySelector('#resultText').textContent=reason; document.querySelector('#resultTime').textContent=formatTime(elapsed); document.querySelector('#resultAlerts').textContent=alerts; beep(win?660:120,.22,win?'sine':'sawtooth',.04); }
  function formatTime(s) { const left=Math.max(0,90-Math.floor(s)); return String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0'); }
  function input() { let x=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0)+touch.x; let y=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0)+touch.y; const len=Math.hypot(x,y); return len>1?{x:x/len,y:y/len}:{x,y}; }
  function distance(a,b) { return Math.hypot(a.x-b.x,a.y-b.y); }
  function nearestHide() { return hideSpots.reduce((best,s)=>!best||distance(player,s)<distance(player,best)?s:best,null); }
  function update(dt) { if(state!=='playing') return; elapsed+=dt; if(elapsed>=90) return finish(false,'終電の時間を過ぎた。次は、もっと暗闇を味方にしよう。'); const dir=input(), sprint=!!(keys.ShiftLeft||keys.ShiftRight||document.querySelector('#sprintButton').dataset.down==='1'); const moving=Math.hypot(dir.x,dir.y)>.05; const speed=sprint&&player.stamina>1?260:150; if(sprint&&moving) player.stamina=Math.max(0,player.stamina-dt*25); else player.stamina=Math.min(100,player.stamina+dt*15); player.x=Math.max(45,Math.min(W-45,player.x+dir.x*speed*dt)); player.y=Math.max(45,Math.min(H-45,player.y+dir.y*speed*dt));
    const near=nearestHide(), nearDist=near?distance(player,near):999; if(keys.KeyE||document.querySelector('#hideButton').dataset.down==='1') { if(nearDist<75) { player.hidden=!player.hidden; keys.KeyE=false; beep(player.hidden?260:520,.1,'sine'); } }
    const d=distance(player,oni); const alertRadius=player.hidden?145:260; if(d<alertRadius) { oni.state='chase'; oni.target={x:player.x,y:player.y}; if(!player.hidden){ alerts=Math.min(9,alerts+dt*1.8); shake=Math.min(9,shake+dt*13); } } else { oni.state='patrol'; oni.target=null; alerts=Math.max(0,alerts-dt*1.1); }
    const angle=Math.atan2((oni.target?oni.target.y:720)-oni.y,(oni.target?oni.target.x:1200)-oni.x); const os=oni.state==='chase'?oni.speed+alerts*10:70; oni.x+=Math.cos(angle)*os*dt; oni.y+=Math.sin(angle)*os*dt; oni.x=Math.max(60,Math.min(W-60,oni.x));oni.y=Math.max(60,Math.min(H-60,oni.y));
    if(d<42&&!player.hidden) return finish(false,'足音が止まった。振り返ると、そこにいた。'); if(player.x>home.x-40&&player.x<home.x+home.w+40&&player.y>home.y-40&&player.y<home.y+home.h+40) return finish(true,'灯りのついた玄関に滑り込んだ。今夜は、あなたの勝ち。'); shake=Math.max(0,shake-dt*18); drawHUD(near,nearDist); }
  function drawHUD(near,dist) { document.querySelector('#timeValue').textContent=formatTime(elapsed); const bar=document.querySelector('#staminaBar');bar.style.width=player.stamina+'%';bar.style.background=player.stamina<25?'var(--danger)':'var(--cyan)'; const level=Math.min(3,Math.floor(alerts/3));document.querySelector('#alertLabel').textContent=level?'DANGER':'QUIET';document.querySelector('#alertLabel').style.color=level?'var(--danger)':'var(--cyan)';document.querySelector('#alertDots').textContent='●'.repeat(level+1)+'○'.repeat(3-level); const prompt=document.querySelector('#hidePrompt'); if(near&&dist<95){prompt.classList.remove('hidden'); const p=worldToScreen(near.x,near.y-68);prompt.style.left=p.x+'px';prompt.style.top=p.y+'px';prompt.querySelector('span').textContent=player.hidden?'出る':'ここに隠れる';}else prompt.classList.add('hidden'); }
  function camera() { return {x:Math.max(0,Math.min(W-innerWidth/scale(),player.x-innerWidth/scale()/2)),y:Math.max(0,Math.min(H-innerHeight/scale(),player.y-innerHeight/scale()/2))}; }
  function scale() { return Math.min(innerWidth/920,innerHeight/600); }
  function worldToScreen(x,y) { const s=scale(),c=camera(); return {x:(x-c.x)*s,y:(y-c.y)*s}; }
  function draw() { const s=scale(),c=camera(); ctx.clearRect(0,0,innerWidth,innerHeight); ctx.save(); ctx.translate(-c.x*s,-c.y*s);ctx.scale(s,s); ctx.fillStyle='#101b29';ctx.fillRect(c.x,c.y,innerWidth/s,innerHeight/s); drawCity(c); drawHome(); hideSpots.forEach(drawHide); drawOni(); drawPlayer(); ctx.restore(); if(shake) { /* screen shake is intentionally subtle; world motion stays readable */ } }
  function drawCity(c) { ctx.fillStyle='#162438';roads.forEach(r=>ctx.fillRect(r.x,r.y,r.w,r.h)); ctx.strokeStyle='rgba(114,214,197,.08)';ctx.lineWidth=2; for(let x=100;x<W;x+=46){ctx.beginPath();ctx.moveTo(x,80);ctx.lineTo(x,H-80);ctx.stroke();} for(let y=100;y<H;y+=46){ctx.beginPath();ctx.moveTo(80,y);ctx.lineTo(W-80,y);ctx.stroke();} buildings.forEach((b,i)=>{ctx.fillStyle=i%3===0?'#1a2a3c':'#1d2e40';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeStyle='rgba(217,238,218,.08)';ctx.strokeRect(b.x,b.y,b.w,b.h);}); lights.forEach(l=>{ctx.fillStyle=`rgba(243,163,77,${.18+.12*Math.sin(elapsed*2+l.phase)})`;ctx.fillRect(l.x,l.y,8,5);}); ctx.fillStyle='rgba(114,214,197,.7)';ctx.font='12px DM Mono';ctx.fillText('烏森駅',130,350);ctx.fillText('灯ヶ丘住宅街',1990,170); }
  function drawHome(){ctx.fillStyle='rgba(243,163,77,.09)';ctx.fillRect(home.x-35,home.y-35,home.w+70,home.h+70);ctx.fillStyle='#263c45';ctx.fillRect(home.x,home.y,home.w,home.h);ctx.fillStyle='#f3a34d';ctx.fillRect(home.x+35,home.y+52,35,55);ctx.fillStyle='#d8a768';ctx.fillRect(home.x+105,home.y+38,32,25);ctx.fillStyle='#dce8d8';ctx.font='14px DM Mono';ctx.fillText('HOME',home.x+58,home.y+22); }
  function drawHide(s){ctx.save();ctx.translate(s.x,s.y);ctx.strokeStyle='rgba(114,214,197,.35)';ctx.setLineDash([5,8]);ctx.beginPath();ctx.arc(0,0,s.r,0,TAU);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#24453f';ctx.beginPath();ctx.arc(-13,4,19,0,TAU);ctx.arc(10,-7,21,0,TAU);ctx.fill();ctx.fillStyle='#75b888';ctx.beginPath();ctx.arc(-17,-12,6,0,TAU);ctx.arc(16,3,7,0,TAU);ctx.fill();ctx.restore();}
  function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);if(player.hidden){ctx.globalAlpha=.35;}ctx.fillStyle='rgba(114,214,197,.2)';ctx.beginPath();ctx.arc(0,0,32+Math.sin(elapsed*5)*3,0,TAU);ctx.fill();ctx.fillStyle='#72d6c5';ctx.beginPath();ctx.arc(0,0,player.r,0,TAU);ctx.fill();ctx.fillStyle='#d9f5df';ctx.beginPath();ctx.arc(5,-5,5,0,TAU);ctx.fill();ctx.restore();}
  function drawOni(){ctx.save();ctx.translate(oni.x,oni.y);const danger=oni.state==='chase';ctx.fillStyle=danger?'rgba(241,115,98,.16)':'rgba(241,115,98,.08)';ctx.beginPath();ctx.arc(0,0,70+(danger?alerts*10:0),0,TAU);ctx.fill();ctx.fillStyle='#2a1d2a';ctx.beginPath();ctx.arc(0,0,oni.r,0,TAU);ctx.fill();ctx.fillStyle=danger?'#f17362':'#b95059';ctx.fillRect(-13,-5,8,5);ctx.fillRect(5,-5,8,5);ctx.fillStyle='#e9c1a0';ctx.beginPath();ctx.arc(0,10,4,0,TAU);ctx.fill();ctx.restore();}
  function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();if(state==='playing')raf=requestAnimationFrame(loop);}
  document.querySelector('#startButton').addEventListener('click',start);document.querySelector('#retryButton').addEventListener('click',start); document.addEventListener('keydown',e=>{keys[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();unlockAudio();});document.addEventListener('keyup',e=>{keys[e.code]=false;});
  function bindButton(id,key){const el=document.querySelector(id);el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);el.dataset.down='1';unlockAudio();});['pointerup','pointercancel','pointerleave'].forEach(ev=>el.addEventListener(ev,()=>el.dataset.down='0'));}
  bindButton('#sprintButton','Shift');bindButton('#hideButton','KeyE');
  const joy=document.querySelector('#joystick'),stick=document.querySelector('#stick');joy.addEventListener('pointerdown',e=>{joy.setPointerCapture(e.pointerId);touch.active=true;joyMove(e);unlockAudio();});joy.addEventListener('pointermove',e=>{if(touch.active)joyMove(e);});['pointerup','pointercancel','pointerleave'].forEach(ev=>joy.addEventListener(ev,()=>{touch.active=false;touch.x=touch.y=0;stick.style.transform='translate(0,0)';}));function joyMove(e){const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.min(35,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);touch.x=Math.cos(a)*m/35;touch.y=Math.sin(a)*m/35;stick.style.transform=`translate(${touch.x*35}px,${touch.y*35}px)`;}
  let lastTap=0;document.addEventListener('touchstart',e=>{const now=Date.now();if(now-lastTap<300)e.preventDefault();lastTap=now;},{passive:false});document.addEventListener('dblclick',e=>e.preventDefault());document.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('resize',resize);resize();draw();
})();
